Create owner model
AY2425S1-CS2103T-T13-3/tp pull request #50
Opened 2024-10-03 05:56 UTC by davidgohzk

Fixes #49

2024-10-09 08:38 UTC, jloh02 requested changes
Thanks for the work! Just a few minor changes

2024-10-09 08:38 UTC, jloh02 commented on src/main/java/seedu/address/model/owner/Address.java
> +     * Returns true if a given string is a valid email.
Do you mean to be a valid landed address? not an email?

2024-10-09 08:38 UTC, jloh02 commented on src/main/java/seedu/address/model/owner/Email.java
> +    public static final String VALIDATION_REGEX = LOCAL_PART_REGEX + "@" + DOMAIN_REGEX;
Thanks for making the validation regex clear by splitting into multiple regexes!

2024-10-09 08:38 UTC, jloh02 commented on src/test/java/seedu/address/model/owner/EmailTest.java
> +    }
Good test coverage of various edge cases!

2024-10-09 08:38 UTC, jloh02 commented on src/main/java/seedu/address/model/owner/Phone.java
> +        "Phone numbers should only contain numbers, and it should be at least 3 digits long";
Perhaps we should also add in that no spaces or + should be added to be clear

2024-10-09 08:38 UTC, jloh02 commented on src/test/java/seedu/address/model/owner/PhoneTest.java
> +        assertFalse(Phone.isValidPhone("9312 1534")); // spaces within digits
Add a test case to test for with country extension e.g. "+198765432"

2024-10-09 15:14 UTC, naythee169 reviewed
LGTM

2024-10-14 16:46 UTC, jloh02 approved these changes

2024-10-14 16:46 UTC, merged